INSERT INTO item (nome, quantidade) VALUES
('Arroz', '1 kg'),
('Feijão', '1 kg'),
('Macarrão', '500 g'),
('Açúcar', '1 kg'),
('Sal', '1 kg'),
('Óleo de soja', '900 ml'),
('Azeite de oliva', '500 ml'),
('Farinha de trigo', '1 kg'),
('Café', '500 g'),
('Molho de tomate', '340 g'),
('Carne bovina', '1 kg'),
('Frango', '1 kg'),
('Ovos', '12 unidades'),
('Leite', '1 litro'),
('Manteiga', '200 g'),
('Queijo muçarela', '300 g'),
('Presunto', '300 g'),
('Iogurte natural', '170 g'),
('Requeijão', '200 g'),
('Creme de leite', '200 g'),
('Maionese', '250 g'),
('Ketchup', '400 g'),
('Mostarda', '200 g'),
('Alface', '1 unidade'),
('Tomate', '5 unidades'),
('Cenoura', '3 unidades'),
('Peito de frango', '1 kg'),
('Margarina', '250 g'),
('Ricota', '300 g'),
('Linguiça', '500 g');